In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
df=pd.read_csv(r'C:\Users\JATIN\OneDrive\Desktop\employee_survey_data.csv')
df.head()

   EmployeeID  EnvironmentSatisfaction  JobSatisfaction  WorkLifeBalance
0           1                      3.0              4.0              2.0
1           2                      3.0              2.0              4.0
2           3                      2.0              2.0              1.0
3           4                      4.0              4.0              3.0
4           5                      4.0              1.0              3.0

In [45]:
df=df.set_index(df.columns[0])
df

            EnvironmentSatisfaction  JobSatisfaction  WorkLifeBalance
EmployeeID
1                               3.0              4.0              2.0
2                               3.0              2.0              4.0
3                               2.0              2.0              1.0
4                               4.0              4.0              3.0
5                               4.0              1.0              3.0
...                             ...              ...              ...
4406                            4.0              1.0              3.0
4407                            4.0              4.0              3.0
4408                            1.0              3.0              3.0
4409                            4.0              1.0              3.0
4410                            1.0              3.0              NaN

[4410 rows x 3 columns]

In [46]:
df.shape

(4410, 3)

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4410 entries, 1 to 4410
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EnvironmentSatisfaction  4385 non-null   float64
 1   JobSatisfaction          4390 non-null   float64
 2   WorkLifeBalance          4372 non-null   float64
dtypes: float64(3)
memory usage: 103.5 KB

In [48]:
df.isnull().sum()

EnvironmentSatisfaction    25
JobSatisfaction            20
WorkLifeBalance            38
dtype: int64

In [49]:
df.describe()

       EnvironmentSatisfaction  JobSatisfaction  WorkLifeBalance
count              4385.000000      4390.000000      4372.000000
mean                  2.723603         2.728246         2.761436
std                   1.092756         1.101253         0.706245
min                   1.000000         1.000000         1.000000
25%                   2.000000         2.000000         2.000000
50%                   3.000000         3.000000         3.000000
75%                   4.000000         4.000000         3.000000
max                   4.000000         4.000000         4.000000

In [50]:
df['EnvironmentSatisfaction'].mean()

np.float64(2.7236031927023947)

In [51]:
df['EnvironmentSatisfaction']=df['EnvironmentSatisfaction'].fillna(df['EnvironmentSatisfaction'].mean(), inplace=True)

C:\Users\JATIN\AppData\Local\Temp\ipykernel_21276\3676878201.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['EnvironmentSatisfaction']=df['EnvironmentSatisfaction'].fillna(df['EnvironmentSatisfaction'].mean(), inplace=True)

In [52]:
df['EnvironmentSatisfaction'].isnull().sum()

np.int64(0)

In [53]:
df['JobSatisfaction']=df['JobSatisfaction'].fillna(df['JobSatisfaction'].mean(), inplace=True)

C:\Users\JATIN\AppData\Local\Temp\ipykernel_21276\427993565.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['JobSatisfaction']=df['JobSatisfaction'].fillna(df['JobSatisfaction'].mean(), inplace=True)

In [54]:
df['JobSatisfaction'].isnull().sum()

np.int64(0)

In [55]:
df['WorkLifeBalance']=df['WorkLifeBalance'].fillna(df['WorkLifeBalance'].mean(), inplace=True)

C:\Users\JATIN\AppData\Local\Temp\ipykernel_21276\1362769317.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['WorkLifeBalance']=df['WorkLifeBalance'].fillna(df['WorkLifeBalance'].mean(), inplace=True)

In [56]:
df['WorkLifeBalance'].isnull().sum()

np.int64(0)

In [57]:
df.head(10)

            EnvironmentSatisfaction  JobSatisfaction  WorkLifeBalance
EmployeeID
1                               3.0              4.0              2.0
2                               3.0              2.0              4.0
3                               2.0              2.0              1.0
4                               4.0              4.0              3.0
5                               4.0              1.0              3.0
6                               3.0              2.0              2.0
7                               1.0              3.0              1.0
8                               1.0              2.0              3.0
9                               2.0              4.0              3.0
10                              2.0              1.0              3.0

In [58]:
df['EnvironmentSatisfaction'] = df['EnvironmentSatisfaction'].round().astype(int)
df['EnvironmentSatisfaction']

EmployeeID
1       3
2       3
3       2
4       4
5       4
       ..
4406    4
4407    4
4408    1
4409    4
4410    1
Name: EnvironmentSatisfaction, Length: 4410, dtype: int64

In [59]:
df['JobSatisfaction']=df['JobSatisfaction'].round().astype(int)
df['JobSatisfaction']

EmployeeID
1       4
2       2
3       2
4       4
5       1
       ..
4406    1
4407    4
4408    3
4409    1
4410    3
Name: JobSatisfaction, Length: 4410, dtype: int64

In [60]:
df['WorkLifeBalance']=df['WorkLifeBalance'].round().astype(int)
df['WorkLifeBalance']

EmployeeID
1       2
2       4
3       1
4       3
5       3
       ..
4406    3
4407    3
4408    3
4409    3
4410    3
Name: WorkLifeBalance, Length: 4410, dtype: int64

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4410 entries, 1 to 4410
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EnvironmentSatisfaction  4410 non-null   int64
 1   JobSatisfaction          4410 non-null   int64
 2   WorkLifeBalance          4410 non-null   int64
dtypes: int64(3)
memory usage: 103.5 KB

In [65]:
df2=pd.read_csv(r'C:\Users\JATIN\OneDrive\Desktop\general_data.csv')
df2.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,4.0,Y,12,8,2,9.0,2,6,0,4

In [105]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      4410 non-null   int64
 1   Attrition                4410 non-null   str
 2   BusinessTravel           4410 non-null   str
 3   Department               4410 non-null   str
 4   DistanceFromHome         4410 non-null   int64
 5   Education                4410 non-null   int64
 6   EducationField           4410 non-null   str
 7   EmployeeCount            4410 non-null   int64
 8   EmployeeID               4410 non-null   int64
 9   Gender                   4410 non-null   str
 10  JobLevel                 4410 non-null   int64
 11  JobRole                  4410 non-null   str
 12  MaritalStatus            4410 non-null   str
 13  MonthlyIncome            4410 non-null   int64
 14  NumCompaniesWorked       4410 non-null   int64
 15  Over18                   4410 non-null   str
 16  PercentSalaryHike        4410 non-null   int64
 17  StandardHours            4410 non-null   int64
 18  StockOptionLevel         4410 non-null   int64
 19  TotalWorkingYears        4410 non-null   int64
 20  TrainingTimesLastYear    4410 non-null   int64
 21  YearsAtCompany           4410 non-null   int64
 22  YearsSinceLastPromotion  4410 non-null   int64
 23  YearsWithCurrManager     4410 non-null   int64
dtypes: int64(16), str(8)
memory usage: 1.1 MB

In [106]:
df2.describe()

,Age,DistanceFromHome,Education,EmployeeCount,EmployeeID,JobLevel,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
count,4410.000000,4410.000000,4410.000000,4410.0,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000,4410.0,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000,4410.000000
mean,36.923810,9.192517,2.912925,1.0,2205.500000,2.063946,65029.312925,2.683220,15.209524,8.0,0.793878,11.279365,2.799320,7.008163,2.187755,4.123129
std,9.133301,8.105026,1.023933,0.0,1273.201673,1.106689,47068.888559,2.499737,3.659108,0.0,0.851883,7.774286,1.288978,6.125135,3.221699,3.567327
min,18.000000,1.000000,1.000000,1.0,1.000000,1.000000,10090.000000,0.000000,11.000000,8.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,2.000000,2.000000,1.0,1103.250000,1.000000,29110.000000,1.000000,12.000000,8.0,0.000000,6.000000,2.000000,3.000000,0.000000,2.000000
50%,36.000000,7.000000,3.000000,1.0,2205.500000,2.000000,49190.000000,2.000000,14.000000,8.0,1.000000,10.000000,3.000000,5.000000,1.000000,3.000000
75%,43.000000,14.000000,4.000000,1.0,3307.750000,3.000000,83800.000000,4.000000,18.000000,8.0,1.000000,15.000000,3.000000,9.000000,3.000000,7.000000
max,60.000000,29.000000,5.000000,1.0,4410.000000,5.000000,199990.000000,9.000000,25.000000,8.0,3.000000,40.000000,6.000000,40.000000,15.000000,17.000000

In [107]:
df2['TotalWorkingYears'].isnull().sum()

np.int64(0)

In [108]:
df2['TotalWorkingYears']=df2['TotalWorkingYears'].fillna(df2['TotalWorkingYears'].mean(), inplace=True)

C:\Users\JATIN\AppData\Local\Temp\ipykernel_21276\2905154136.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2['TotalWorkingYears']=df2['TotalWorkingYears'].fillna(df2['TotalWorkingYears'].mean(), inplace=True)

In [109]:
df2['TotalWorkingYears']=df2['TotalWorkingYears'].round().astype(int)
df2['TotalWorkingYears']

0        1
1        6
2        5
3       13
4        9
        ..
4405    10
4406    10
4407     5
4408    10
4409    11
Name: TotalWorkingYears, Length: 4410, dtype: int64

In [110]:
df2['NumCompaniesWorked'].sample(10)

3815    5
1141    1
1824    1
326     1
3692    2
3975    4
394     1
3369    4
1441    1
845     8
Name: NumCompaniesWorked, dtype: int64

In [111]:
df2['NumCompaniesWorked']=df2['NumCompaniesWorked'].fillna((0),inplace=True)

C:\Users\JATIN\AppData\Local\Temp\ipykernel_21276\4284660336.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2['NumCompaniesWorked']=df2['NumCompaniesWorked'].fillna((0),inplace=True)

In [112]:
df2['NumCompaniesWorked']=df2['NumCompaniesWorked'].round().astype(int)
df2['NumCompaniesWorked']

0       1
1       0
2       1
3       3
4       4
       ..
4405    3
4406    2
4407    0
4408    0
4409    0
Name: NumCompaniesWorked, Length: 4410, dtype: int64

In [113]:
df2.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1,Y,11,8,0,1,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0,Y,23,8,1,6,3,5,1,4
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1,Y,15,8,3,5,2,5,0,3
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3,Y,11,8,3,13,5,8,7,5
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,4,Y,12,8,2,9,2,6,0,4

In [114]:
df2['BusinessTravel'].value_counts()

BusinessTravel
Travel_Rarely        3129
Travel_Frequently     831
Non-Travel            450
Name: count, dtype: int64

In [116]:
df3=pd.read_csv(r'C:\Users\JATIN\OneDrive\Desktop\manager_survey_data.csv')
df3.head()

   EmployeeID  JobInvolvement  PerformanceRating
0           1               3                  3
1           2               2                  4
2           3               3                  3
3           4               2                  3
4           5               3                  3

In [117]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         4410 non-null   int64
 1   JobInvolvement     4410 non-null   int64
 2   PerformanceRating  4410 non-null   int64
dtypes: int64(3)
memory usage: 103.5 KB

In [119]:
df.describe()

       EnvironmentSatisfaction  JobSatisfaction  WorkLifeBalance
count              4410.000000      4410.000000      4410.000000
mean                  2.725170         2.729478         2.763492
std                   1.089852         1.098904         0.703541
min                   1.000000         1.000000         1.000000
25%                   2.000000         2.000000         2.000000
50%                   3.000000         3.000000         3.000000
75%                   4.000000         4.000000         3.000000
max                   4.000000         4.000000         4.000000

In [121]:
df4=pd.read_csv(r'C:\Users\JATIN\OneDrive\Desktop\HR_Analytics_Cleaned_Master.csv')
df4.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeID,Gender,JobLevel,...,EnvironmentSatisfaction,JobSatisfaction,WorkLifeBalance,JobInvolvement,PerformanceRating,Education_Label,JobSatisfaction_Label,EnvironmentSatisfaction_Label,WorkLifeBalance_Label,PerformanceRating_Label
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,Female,1,...,3.0,4.0,2.0,3,3,College,Very High,High,Good,Excellent
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,2,Female,1,...,3.0,2.0,4.0,2,4,Below College,Medium,High,Best,Outstanding
2,32,No,Travel_Frequently,Research & Development,17,4,Other,3,Male,4,...,2.0,2.0,1.0,3,3,Master,Medium,Medium,Bad,Excellent
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,4,Male,3,...,4.0,4.0,3.0,2,3,Doctor,Very High,Very High,Better,Excellent
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,5,Male,1,...,4.0,1.0,3.0,3,3,Below College,Low,Very High,Better,Excellent

In [133]:
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 4327 entries, 0 to 4326
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            4327 non-null   int64
 1   Attrition                      4327 non-null   str
 2   BusinessTravel                 4327 non-null   str
 3   Department                     4327 non-null   str
 4   DistanceFromHome               4327 non-null   int64
 5   Education                      4327 non-null   int64
 6   EducationField                 4327 non-null   str
 7   EmployeeID                     4327 non-null   int64
 8   Gender                         4327 non-null   str
 9   JobLevel                       4327 non-null   int64
 10  JobRole                        4327 non-null   str
 11  MaritalStatus                  4327 non-null   str
 12  MonthlyIncome                  4327 non-null   int64
 13  NumCompaniesWorked             4327 non-null   float64
 14  PercentSalaryHike              4327 non-null   int64
 15  StockOptionLevel               4327 non-null   int64
 16  TotalWorkingYears              4327 non-null   float64
 17  TrainingTimesLastYear          4327 non-null   int64
 18  YearsAtCompany                 4327 non-null   int64
 19  YearsSinceLastPromotion        4327 non-null   int64
 20  YearsWithCurrManager           4327 non-null   int64
 21  EnvironmentSatisfaction        4327 non-null   int64
 22  JobSatisfaction                4327 non-null   float64
 23  WorkLifeBalance                4327 non-null   float64
 24  JobInvolvement                 4327 non-null   int64
 25  PerformanceRating              4327 non-null   int64
 26  Education_Label                4327 non-null   str
 27  JobSatisfaction_Label          4327 non-null   str
 28  EnvironmentSatisfaction_Label  4327 non-null   str
 29  WorkLifeBalance_Label          4327 non-null   str
 30  PerformanceRating_Label        4327 non-null   str
dtypes: float64(4), int64(15), str(12)
memory usage: 1.5 MB

In [134]:
df4.isnull().sum()

Age                              0
Attrition                        0
BusinessTravel                   0
Department                       0
DistanceFromHome                 0
Education                        0
EducationField                   0
EmployeeID                       0
Gender                           0
JobLevel                         0
JobRole                          0
MaritalStatus                    0
MonthlyIncome                    0
NumCompaniesWorked               0
PercentSalaryHike                0
StockOptionLevel                 0
TotalWorkingYears                0
TrainingTimesLastYear            0
YearsAtCompany                   0
YearsSinceLastPromotion          0
YearsWithCurrManager             0
EnvironmentSatisfaction          0
JobSatisfaction                  0
WorkLifeBalance                  0
JobInvolvement                   0
PerformanceRating                0
Education_Label                  0
JobSatisfaction_Label            0
EnvironmentSatisfaction_Label    0
WorkLifeBalance_Label            0
PerformanceRating_Label          0
dtype: int64

In [135]:
df4['EnvironmentSatisfaction'].info()

<class 'pandas.Series'>
RangeIndex: 4327 entries, 0 to 4326
Series name: EnvironmentSatisfaction
Non-Null Count  Dtype
--------------  -----
4327 non-null   int64
dtypes: int64(1)
memory usage: 33.9 KB

In [136]:
df4['EnvironmentSatisfaction']=df4['EnvironmentSatisfaction'].round().astype(int)
df4['EnvironmentSatisfaction']

0       3
1       3
2       2
3       4
4       4
       ..
4322    3
4323    4
4324    4
4325    1
4326    4
Name: EnvironmentSatisfaction, Length: 4327, dtype: int64

In [137]:
df4['JobSatisfaction']=df4['JobSatisfaction'].round().astype(int)
df4['JobSatisfaction']

0       4
1       2
2       2
3       4
4       1
       ..
4322    4
4323    1
4324    4
4325    3
4326    1
Name: JobSatisfaction, Length: 4327, dtype: int64

In [138]:
df4['WorkLifeBalance']=df4['WorkLifeBalance'].round().astype(int)
df4['WorkLifeBalance']

0       2
1       4
2       1
3       3
4       3
       ..
4322    3
4323    3
4324    3
4325    3
4326    3
Name: WorkLifeBalance, Length: 4327, dtype: int64

In [139]:
df4.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeID,Gender,JobLevel,...,EnvironmentSatisfaction,JobSatisfaction,WorkLifeBalance,JobInvolvement,PerformanceRating,Education_Label,JobSatisfaction_Label,EnvironmentSatisfaction_Label,WorkLifeBalance_Label,PerformanceRating_Label
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,Female,1,...,3,4,2,3,3,College,Very High,High,Good,Excellent
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,2,Female,1,...,3,2,4,2,4,Below College,Medium,High,Best,Outstanding
2,32,No,Travel_Frequently,Research & Development,17,4,Other,3,Male,4,...,2,2,1,3,3,Master,Medium,Medium,Bad,Excellent
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,4,Male,3,...,4,4,3,2,3,Doctor,Very High,Very High,Better,Excellent
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,5,Male,1,...,4,1,3,3,3,Below College,Low,Very High,Better,Excellent

In [ ]:
c

NameError: name 'pd' is not defined